### ISSUE TITLE
Move the update_totals method to the Invoices itself

### ISSUE THREAD

**Issue by cdvv7788** [swappsco/accountant#1]
We should move this to the invoice itself, to avoid potential race conditions and potentially recalculating this several times.
Also, once the invoice is not in draft, we should prevent it from being saved, so we are forced to use the invoices the right way (making it void, creating a new one, etc).
What do you think @andresgz ?

**Comment by cdvv7788** [comment]
Currently it is updating when an InvoiceLine is saving, not an Invoice, so when you add a new invoice with several items it will not update. However now that i think about it whenever i create a new invoice it will not have the right values because the invoice line items will not exist yet. Still, there may be a better way.
About the lock of the invoices, we could keep it editable until user decides it is the definite one. If after that he wants to edit it, we can create a copy and assign a new consecutive, make void the old one, etc.

**Comment by andresgz** [comment]
Agreed.
Dealing with this on Django Admin It is not very friendly, so we will improve this implementation when we do it in the front side, where it should have lot of Javascript interactions and we have more control on the view.

Discussion about the restrictions on the invoice should be left on another issue.
